name: GCC x86_64 Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake gcovr jq

      - name: Configure with CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DSOFAB_ENABLE_COVERAGE=ON

      - name: Build project
        run: cmake --build build

      - name: Verify C binary
        working-directory: build/test/c/
        run: |
          file sofabtest
          readelf -h -A sofabtest

      - name: Verify C++ binary
        working-directory: build/test/cpp/
        run: |
          file sofabpptest
          readelf -h -A sofabpptest

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure --verbose

      - name: Test coverage report
        run: |
          gcovr \
            --root . \
            --filter '^src/.*\.(c|h)$' \
            --exclude-directories '.*/_deps/.*' \
            --object-directory build

      - name: Test coverage badge JSON
        run: |
          gcovr \
            --root . \
            --filter '^src/.*\.(c|h)$' \
            --exclude-directories '.*/_deps/.*' \
            --object-directory build \
            --json-summary coverage.json
          jq -n --argjson cov "$(<coverage.json)" '
            ($cov.line_covered / $cov.line_total * 100) as $pct |
            {
              schemaVersion: 1,
              label: "gcovr",
              message: ($pct | tostring[0:4] + "%"),
              color: (if $pct >= 90 then "brightgreen" elif $pct >= 75 then "yellow" else "red" end)
            }
          ' > badge.json
          echo "$(<badge.json)"

#      - name: Upload artifact for GitHub Pages
#        uses: actions/upload-pages-artifact@v3
#        with:
#          path: badge.json